### ISSUE TITLE
ensembl_gene_information

### ISSUE THREAD

**Issue by kbsssu** [adriaan-vd-graaf/genome_integration#2]
Hi,
I have a question about gene information.
The "--ensg_id" is required parameter for running MRlink and MRlink utilize "genome_integration/resources/ensembl_data/2018_05_18_ensembl_gene_information.txt.gz" file.
Is there any way to update the ensembl gene information file or use user specific file?
Because of the required "--ensg_id" option, it is impossible to analyze using other resources instead of eQTL as exposure variable.

Best wishes,
Beomsu Kim.

**Comment by adriaan-vd-graaf** [comment]
Hi Beomsu Kim,

I've added the functionality to the package. Please use the `--region` option instead of the `--ensg_id` option to specify the region. `--region` accepts all genetic regions in the format of `<chr>:<start>-<end>`. I've added some rudimentary tests, and they work on my machine. 
I'm very interested in your experience running it.

Best wishes, Adriaan

**Comment by kbsssu** [comment]
I'm so sorry for the late reply.
I'm really appreciate your quik response and kind code update.
Because of other steps of my research, I'll check `--region` option later and share my experience.

By the way, I have a new question.
Is it okay to use summary statistics file with IV SNPs only for `--exposure_summary_statistics`? As far as I understand, all cis-SNPs information for estimating nuisance parameters (β_u * b_u) would be file if only in the `--reference_bed` and `--outcome_phenotype_file`.

Best wishes,
Beomsu kim.

**Comment by adriaan-vd-graaf** [comment]
Dear Beomsu Kim,

It's generally best to use the full summary statistics file so that GCTA-COJO can identify the best SNPs that can be used as IVs. In our simulations IV selection using GCTA COJO generally provided the best results. If, for some other reason you'd like to use other forms of IV selection, it is not possible now, but I could implement something like a SNP selection option quite quickly.

Short answer: It's currently not possible to supply your self selected variants as IVs, but it could be in the future.

best wishes, 
Adriaan

**Comment by kbsssu** [comment]
Dear Adriaan-vd-graaf,

Thanks to clarify my curiosity.
Actually, I have a eQTL summary statistics file with only SNPs that passed conditional analysis. I'll try to access the full summary statistics file.
Thank you so much!

Best wishes,
Beomsu Kim.

**Comment by adriaan-vd-graaf** [comment]
Thanks for your interest! 
I'm closing this issue now. Please don't hesitate to ask any questions though!
best wishes, Adriaan
